apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: web-demo
type: Opaque
# 小技巧：使用 stringData 而不是 data
# K8s 会在底层自动帮你把 stringData 里的明文转换成 Base64 编码存入 etcd
# 这样你就不用每次手工去执行 `echo -n "xxx" | base64` 了，极大提升运维幸福感
stringData:
  POSTGRES_USER: "demo_admin"
  POSTGRES_PASSWORD: "demo_password_123!"
  POSTGRES_DB: "webdemo_db"