import http from 'k6/http';
import { check } from 'k6';
import exec from 'k6/execution';

let errorCount = 0;

export const options = {
  vus: __ENV.VUS ? parseInt(__ENV.VUS) : 200,
  duration: __ENV.DURATION || '30s',
  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(90)', 'p(95)', 'p(99)'],
};

export default function () {
  // Random user ID (1-10000) mimicking reality
  const userId = Math.floor(Math.random() * 10000) + 1;
  // Random article ID (1-200)
  const articleId = Math.floor(Math.random() * 200) + 1;
  // Payload for new comment
  const payload = JSON.stringify({
    user_id: userId,
    article_id: articleId,
    content: `This is a tremendous load testing comment generated by a virtual user. Let's see how much synchronous disk io we can pull off!!! (UserID: ${userId})`
  });
  
  const params = {
    headers: { 'Content-Type': 'application/json' },
  };
  
  const baseUrl = __ENV.BASE_URL || 'http://app:8080';
  const res = http.post(`${baseUrl}/comments`, payload, params);

  if (res.status !== 201) {
    if (errorCount < 3) {
      console.error(`[VU ${exec.vu.idInTest}] Post Comment Failed. Status: ${res.status}, Error: ${res.error}, Body: ${res.body}`);
      errorCount++;
    }
  }
  
  check(res, {
    'is created status 201': (r) => r.status === 201,
  });
}
