server {
    listen 80;
    server_name localhost;

    # 静态文件根目录
    root /usr/share/nginx/html;
    index index.html;

    # 静态资源请求
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API 请求代理
    # 用于 docker-compose 启动时直接用 nginx 将请求代理给 backend。
    # 在 Kubernetes Ingress 中该配置不是必需的，因为 Ingress 将配置 /api 的路由。
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
