import http from 'k6/http';
import { check } from 'k6';
import exec from 'k6/execution';

let errorCount = 0;

export const options = {
  vus: __ENV.VUS ? parseInt(__ENV.VUS) : 200,
  duration: __ENV.DURATION || '30s',
  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(90)', 'p(95)', 'p(99)'],
};

export function setup() {
  const maxOpen = __ENV.DB_MAX_OPEN ? parseInt(__ENV.DB_MAX_OPEN) : null;
  const baseUrl = __ENV.BASE_URL || 'http://app:8080';
  
  if (maxOpen) {
    // We adjust both max_open and max_idle to the same value to prevent connection thrashing
    const payload = JSON.stringify({ max_open: maxOpen, max_idle: maxOpen });
    const params = { headers: { 'Content-Type': 'application/json' } };
    const res = http.put(`${baseUrl}/config/db-pool`, payload, params);
    
    if (res.status === 200) {
      console.log(`[*] Setup: Auto-tuning DB Pool (MaxOpen) to ${maxOpen} SUCCESS`);
    } else {
      console.error(`[!] Setup: Failed to tune DB Pool to ${maxOpen}: ${res.status} ${res.body}`);
    }
  }
}

export default function () {
  // Random user ID (1-10000) mimicking reality
  const userId = Math.floor(Math.random() * 10000) + 1;
  // Random article ID (1-200)
  const articleId = Math.floor(Math.random() * 200) + 1;
  // Payload for new comment
  const payload = JSON.stringify({
    user_id: userId,
    article_id: articleId,
    content: `This is a tremendous load testing comment generated by a virtual user. Let's see how much synchronous disk io we can pull off!!! (UserID: ${userId})`
  });
  
  const params = {
    headers: { 'Content-Type': 'application/json' },
  };
  
  const baseUrl = __ENV.BASE_URL || 'http://app:8080';
  const res = http.post(`${baseUrl}/comments`, payload, params);

  if (res.status !== 201) {
    if (errorCount < 3) {
      console.error(`[VU ${exec.vu.idInTest}] Post Comment Failed. Status: ${res.status}, Error: ${res.error}, Body: ${res.body}`);
      errorCount++;
    }
  }
  
  check(res, {
    'is created status 201': (r) => r.status === 201,
  });
}
